version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - grocery-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # Replace with your email ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD:  ${PGADMIN_DEFAULT_PASSWORD} # Replace with your password ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"

volumes:
  grocery-postgres-data:
